<a href="https://colab.research.google.com/github/RosalesLuis123/IA/blob/main/Lab5/Redes_Neuronales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/

# **IMPORTAMOS LIBRERIAS**

In [ ]:
# used for manipulating directory paths
import os

# Scientific and vector computation for python
import numpy as np

# Plotting library
from matplotlib import pyplot
import pandas as pd
# Optimization module in scipy
from scipy import optimize

# will be used to load MATLAB mat datafile format
# from scipy.io import loadmat

# library written for this exercise providing additional functions for assignment submission, and others
# import utils


# tells matplotlib to embed plots within the notebook
%matplotlib inline

# **LEEMOS EL DATA SET**

Informacion del dataset

In [ ]:
data = pd.read_csv('/content/gdrive/MyDrive/Laboratorio5/lol.csv', delimiter=',')
data

,MatchID,Time,Player1_X,Player1_Y,Player2_X,Player2_Y,Player3_X,Player3_Y,Player4_X,Player4_Y,...,Distance_6_8,Distance_6_9,Distance_6_10,Distance_7_8,Distance_7_9,Distance_7_10,Distance_8_9,Distance_8_10,Distance_9_10,Teamfight
0,NA1_4647454701,0,554.000000,581.000000,593.000000,464.000000,557.000000,345.000000,458.000000,271.000000,...,236.019067,324.524267,381.188930,124.326184,235.529191,323.402226,123.600162,234.648674,123.016259,0
1,NA1_4647454701,1,596.566667,751.083333,753.550000,576.266667,663.883333,455.516667,594.266667,340.750000,...,317.620765,398.464944,352.764776,114.265467,208.005594,212.190015,102.462882,161.464004,120.356600,0
2,NA1_4647454701,2,639.133333,921.166667,914.100000,688.533333,770.766667,566.033333,730.533333,410.500000,...,425.035137,538.710973,422.569696,133.519741,247.509813,144.642352,120.403636,88.876494,130.992536,0
3,NA1_4647454701,3,681.700000,1091.250000,1074.650000,800.800000,877.650000,676.550000,866.800000,480.250000,...,543.158128,706.839163,554.681424,172.539191,330.844892,179.664750,165.142908,23.349946,152.161099,0
4,NA1_4647454701,4,724.266667,1261.333333,1235.200000,913.066667,984.533333,787.066667,1003.066667,550.000000,...,666.318696,887.136169,715.375420,221.095796,433.425923,281.244804,220.961706,63.318174,180.187618,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459402,NA1_4648707043,1016,2512.866667,11896.000000,2050.333333,11544.000000,10844.800000,1633.200000,6612.600000,7280.533333,...,11900.077544,7679.229450,12179.584381,5505.489785,1566.879793,7289.087073,4520.089254,5612.027286,7562.516578,0
459403,NA1_4648707043,1017,2514.900000,11893.750000,2029.000000,11545.000000,10834.350000,1627.900000,6601.450000,7264.900000,...,11903.895166,7683.561913,12180.284396,5506.981257,1567.367557,7290.266515,4520.162262,5612.929153,7562.516578,0
459404,NA1_4648707043,1018,2516.933333,11891.500000,2007.666667,11546.000000,10823.900000,1622.600000,6590.300000,7249.266667,...,11907.715988,7687.897193,12180.987691,5508.472749,1567.856266,7291.446002,4520.235455,5613.831024,7562.516578,0
459405,NA1_4648707043,1019,2518.966667,11889.250000,1986.333333,11547.000000,10813.450000,1617.300000,6579.150000,7233.633333,...,11911.540007,7692.235286,12181.694264,5509.964262,1568.345918,7292.625534,4520.308833,5614.732900,7562.516578,0
459406,NA1_4648707043,1020,2521.000000,11887.000000,1965.000000,11548.000000,10803.000000,1612.000000,6568.000000,7218.000000,...,11915.367221,7696.576187,12182.404114,5511.455797,1568.836512,7293.805111,4520.382395,5615.634782,7562.516578,0

In [ ]:
# Eliminar la primera fila
data = data.drop(data.columns[0], axis=1)

# Ahora `data` contiene el DataFrame sin la primera fil
data

,Time,Player1_X,Player1_Y,Player2_X,Player2_Y,Player3_X,Player3_Y,Player4_X,Player4_Y,Player5_X,...,Distance_6_8,Distance_6_9,Distance_6_10,Distance_7_8,Distance_7_9,Distance_7_10,Distance_8_9,Distance_8_10,Distance_9_10,Teamfight
0,0,554.000000,581.000000,593.000000,464.000000,557.000000,345.000000,458.000000,271.000000,335.000000,...,236.019067,324.524267,381.188930,124.326184,235.529191,323.402226,123.600162,234.648674,123.016259,0
1,1,596.566667,751.083333,753.550000,576.266667,663.883333,455.516667,594.266667,340.750000,477.616667,...,317.620765,398.464944,352.764776,114.265467,208.005594,212.190015,102.462882,161.464004,120.356600,0
2,2,639.133333,921.166667,914.100000,688.533333,770.766667,566.033333,730.533333,410.500000,620.233333,...,425.035137,538.710973,422.569696,133.519741,247.509813,144.642352,120.403636,88.876494,130.992536,0
3,3,681.700000,1091.250000,1074.650000,800.800000,877.650000,676.550000,866.800000,480.250000,762.850000,...,543.158128,706.839163,554.681424,172.539191,330.844892,179.664750,165.142908,23.349946,152.161099,0
4,4,724.266667,1261.333333,1235.200000,913.066667,984.533333,787.066667,1003.066667,550.000000,905.466667,...,666.318696,887.136169,715.375420,221.095796,433.425923,281.244804,220.961706,63.318174,180.187618,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459402,1016,2512.866667,11896.000000,2050.333333,11544.000000,10844.800000,1633.200000,6612.600000,7280.533333,6612.600000,...,11900.077544,7679.229450,12179.584381,5505.489785,1566.879793,7289.087073,4520.089254,5612.027286,7562.516578,0
459403,1017,2514.900000,11893.750000,2029.000000,11545.000000,10834.350000,1627.900000,6601.450000,7264.900000,6601.450000,...,11903.895166,7683.561913,12180.284396,5506.981257,1567.367557,7290.266515,4520.162262,5612.929153,7562.516578,0
459404,1018,2516.933333,11891.500000,2007.666667,11546.000000,10823.900000,1622.600000,6590.300000,7249.266667,6590.300000,...,11907.715988,7687.897193,12180.987691,5508.472749,1567.856266,7291.446002,4520.235455,5613.831024,7562.516578,0
459405,1019,2518.966667,11889.250000,1986.333333,11547.000000,10813.450000,1617.300000,6579.150000,7233.633333,6579.150000,...,11911.540007,7692.235286,12181.694264,5509.964262,1568.345918,7292.625534,4520.308833,5614.732900,7562.516578,0
459406,1020,2521.000000,11887.000000,1965.000000,11548.000000,10803.000000,1612.000000,6568.000000,7218.000000,6568.000000,...,11915.367221,7696.576187,12182.404114,5511.455797,1568.836512,7293.805111,4520.382395,5615.634782,7562.516578,0

Informacion del dataset

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 459407 entries, 0 to 459406
Data columns (total 67 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Time           459407 non-null  int64
 1   Player1_X      459407 non-null  float64
 2   Player1_Y      459407 non-null  float64
 3   Player2_X      459407 non-null  float64
 4   Player2_Y      459407 non-null  float64
 5   Player3_X      459407 non-null  float64
 6   Player3_Y      459407 non-null  float64
 7   Player4_X      459407 non-null  float64
 8   Player4_Y      459407 non-null  float64
 9   Player5_X      459407 non-null  float64
 10  Player5_Y      459407 non-null  float64
 11  Player6_X      459407 non-null  float64
 12  Player6_Y      459407 non-null  float64
 13  Player7_X      459407 non-null  float64
 14  Player7_Y      459407 non-null  float64
 15  Player8_X      459407 non-null  float64
 16  Player8_Y      459407 non-null  float64
 17  Player9_X      459407 non-null  float64
 18  Player9_Y      459407 non-null  float64
 19  Player10_X     459407 non-null  float64
 20  Player10_Y     459407 non-null  float64
 21  Distance_1_2   459407 non-null  float64
 22  Distance_1_3   459407 non-null  float64
 23  Distance_1_4   459407 non-null  float64
 24  Distance_1_5   459407 non-null  float64
 25  Distance_1_6   459407 non-null  float64
 26  Distance_1_7   459407 non-null  float64
 27  Distance_1_8   459407 non-null  float64
 28  Distance_1_9   459407 non-null  float64
 29  Distance_1_10  459407 non-null  float64
 30  Distance_2_3   459407 non-null  float64
 31  Distance_2_4   459407 non-null  float64
 32  Distance_2_5   459407 non-null  float64
 33  Distance_2_6   459407 non-null  float64
 34  Distance_2_7   459407 non-null  float64
 35  Distance_2_8   459407 non-null  float64
 36  Distance_2_9   459407 non-null  float64
 37  Distance_2_10  459407 non-null  float64
 38  Distance_3_4   459407 non-null  float64
 39  Distance_3_5   459407 non-null  float64
 40  Distance_3_6   459407 non-null  float64
 41  Distance_3_7   459407 non-null  float64
 42  Distance_3_8   459407 non-null  float64
 43  Distance_3_9   459407 non-null  float64
 44  Distance_3_10  459407 non-null  float64
 45  Distance_4_5   459407 non-null  float64
 46  Distance_4_6   459407 non-null  float64
 47  Distance_4_7   459407 non-null  float64
 48  Distance_4_8   459407 non-null  float64
 49  Distance_4_9   459407 non-null  float64
 50  Distance_4_10  459407 non-null  float64
 51  Distance_5_6   459407 non-null  float64
 52  Distance_5_7   459407 non-null  float64
 53  Distance_5_8   459407 non-null  float64
 54  Distance_5_9   459407 non-null  float64
 55  Distance_5_10  459407 non-null  float64
 56  Distance_6_7   459407 non-null  float64
 57  Distance_6_8   459407 non-null  float64
 58  Distance_6_9   459407 non-null  float64
 59  Distance_6_10  459407 non-null  float64
 60  Distance_7_8   459407 non-null  float64
 61  Distance_7_9   459407 non-null  float64
 62  Distance_7_10  459407 non-null  float64
 63  Distance_8_9   459407 non-null  float64
 64  Distance_8_10  459407 non-null  float64
 65  Distance_9_10  459407 non-null  float64
 66  Teamfight      459407 non-null  int64
dtypes: float64(65), int64(2)
memory usage: 234.8 MB

Verificamos la cantidad de clases en la columna income la cual sera Y

In [ ]:
import pandas as pd

# Suponiendo que 'data' es tu DataFrame de pandas
# Seleccionamos la columna 'income'
columna_income = data['Teamfight']

# Usamos el método nunique() para obtener el número de clases únicas en la columna 'income'
num_clases_income = columna_income.nunique()

# Obtenemos los valores únicos de la columna 'income'
valores_clases_income = columna_income.unique()

print("Cantidad de clases en la columna 'income':", num_clases_income)
print("Valores de las clases en la columna 'income':", valores_clases_income)

Cantidad de clases en la columna 'income': 2
Valores de las clases en la columna 'income': [0 1]

# **Preparamos los valores para el entrenmaiento:** se ajustan las clases y se normaliza

In [ ]:
# Suponiendo que 'data' es tu DataFrame de pandas

# Seleccionar todas las filas y todas las columnas excepto la última
X = data.iloc[:, :-1].values

# Seleccionar la última columna
y = data.iloc[:, -1].values

# Normalizar las características
X_mean = np.mean(X, axis=0)
X_std = np.std(X, axis=0)
X_normalized = (X - X_mean) / X_std

# Imprimir las primeras 5 filas de las características normalizadas
print("Características normalizadas:")
print(X_normalized[:5])

y = np.array([int(e) for e in y])
print(y.shape)
y = np.squeeze(y)

y[y == 0] = 0
y[y == 1] = 1

Xp = X_normalized[150:, :]
X_normalized = X_normalized[:150, :]

yp = y[150:]
y = y[:150]

print(X_normalized.shape)
print(y.shape)
print(Xp.shape)
print(yp.shape)

print(y)

Características normalizadas:
[[-1.5959249  -1.17458742 -2.20518607 -2.04407013 -2.14041627 -2.23112375
  -2.18312935 -2.34999152 -1.38362489 -2.25803975 -1.53518486  2.24166102
   1.24817451  2.16060748  2.13260054  2.18179455  2.22988729  1.32219341
   2.32965649  1.42585259  2.21930861 -1.56702705 -1.81973776 -1.61999612
  -1.52904915  3.9995101   3.63294479  3.78206915  2.36525852  2.48981317
  -1.41684056 -1.36863613 -1.21539813  3.63720145  4.57837829  4.61992656
   3.824718    3.90096292 -1.78374402 -1.50827677  3.89687752  4.69437231
   4.39619171  4.26321379  4.2632236  -0.92655371  2.45662792  3.92620787
   4.36667671  4.52696088  4.35635498  2.63017196  4.04452112  4.31279353
   4.41130696  4.34684909 -1.59760538 -1.85376486 -1.63447989 -1.56004827
  -1.42136415 -1.36223068 -1.22262049 -1.76843359 -1.50236551 -0.93197443]
 [-1.59403433 -1.16132909 -2.15825189 -1.98712441 -2.09908918 -2.19166252
  -2.14193207 -2.30925255 -1.35990445 -2.21533687 -1.5046422   2.18231014
   1.23765344  2.10135851  2.09691642  2.14456023  2.19620087  1.30908127
   2.29467692  1.41563424  2.19659525 -1.53448717 -1.7984133  -1.60164691
  -1.52251636  3.91345966  3.54104697  3.69894347  2.30881779  2.43984846
  -1.40640288 -1.35333953 -1.20627136  3.53599005  4.46157264  4.51656468
   3.74051235  3.82624501 -1.77988212 -1.51688939  3.79992707  4.58830294
   4.31272148  4.18190058  4.19366199 -0.9285236   2.38649183  3.8344017
   4.2782027   4.45279329  4.29371785  2.55444543  3.94773976  4.22236374
   4.33366085  4.28035119 -1.57322846 -1.82797781 -1.61856075 -1.56630237
  -1.42535685 -1.3709806  -1.25823239 -1.77611183 -1.52832249 -0.93301545]
 [-1.59214376 -1.14807077 -2.11131771 -1.93017869 -2.05776208 -2.15220128
  -2.10073479 -2.26851357 -1.33618401 -2.17263399 -1.47409953  2.12295927
   1.22713236  2.04210954  2.0612323   2.1073259   2.16251445  1.29596912
   2.25969734  1.40541589  2.1738819  -1.49798606 -1.77439077 -1.57845971
  -1.50845699  3.82743187  3.44918444  3.615934    2.25262722  2.39006356
  -1.39113307 -1.33802733 -1.19709489  3.43518493  4.3448666   4.41322885
   3.6563127   3.75152726 -1.77028331 -1.52330716  3.70324114  4.48226246
   4.22925144  4.10063878  4.12411787 -0.9292546   2.31672519  3.74271699
   4.18977504  4.37862633  4.23108485  2.47905382  3.85105355  4.13196296
   4.2560188   4.21385397 -1.5480936  -1.79403367 -1.58836634 -1.55094335
  -1.41771559 -1.35842196 -1.27986221 -1.76959475 -1.55406767 -0.92885244]
 [-1.5902532  -1.13481245 -2.06438354 -1.87323298 -2.01643499 -2.11274005
  -2.0595375  -2.2277746  -1.31246356 -2.12993111 -1.44355687  2.06360839
   1.21661129  1.98286057  2.02554818  2.07009158  2.12882802  1.28285698
   2.22471776  1.39519754  2.15116854 -1.46053709 -1.74899841 -1.55287796
  -1.4894244   3.74142793  3.35735909  3.53304607  2.19669707  2.34046486
  -1.37337594 -1.32270553 -1.1878792   3.33481021  4.2282662   4.30992046
   3.57211933  3.67680968 -1.75722436 -1.52687477  3.60683364  4.37625241
   4.14578162  4.01943054  4.05459189 -0.9286862   2.24734671  3.65116008
   4.10139578  4.30446003  4.16845614  2.40401505  3.75446771  4.04159255
   4.17838099  4.14735744 -1.52271408 -1.75670549 -1.552169   -1.52187509
  -1.4022303  -1.33192922 -1.26864749 -1.75334295 -1.57730848 -0.92056686]
 [-1.58836263 -1.12155412 -2.01744936 -1.81628726 -1.97510789 -2.07327882
  -2.01834022 -2.18703562 -1.28874312 -2.08722823 -1.4130142   2.00425752
   1.20609022  1.9236116   1.98986406  2.03285725  2.0951416   1.26974484
   2.18973818  1.38497918  2.12845519 -1.4227301  -1.72284225 -1.52602275
  -1.46736236  3.65544912  3.26557295  3.45028532  2.14103812  2.29105907
  -1.35430524 -1.30737739 -1.17863204  3.23489185  4.11177801  4.20664098
   3.48793255  3.60209228 -1.74226048 -1.52711802  3.5107194   4.27027447
   4.06231202  3.93827812  3.9850847  -0.92686577  2.17837625  3.55973771
   4.01306711  4.2302944   4.10583186  2.32934825  3.65798783  3.95125399
   4.10074762  4.08086164 -1.49722622 -1.71778537 -1.51335177 -1.48651793
  -1.38296008 -1.29931806 -1.23611996 -1.73306644 -1.56313263 -0.90959702]]
(459407,)
(150, 66)
(150,)
(459257, 66)
(459257,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]

In [ ]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]

Preparar valores iniciales de la red neuronal

In [ ]:
# Configurando parámetros necesarios
input_layer_size = 66   # Entrada de 14 características
hidden_layer_size = 15  # 10 unidades ocultas
num_labels = 2         # 3 etiquetas, de 0 a 2

# Inicializando los pesos Theta1 y Theta2
Theta1 = np.random.rand(hidden_layer_size, input_layer_size + 1)  # Theta1 tiene un tamaño de (10, 15)
Theta2 = np.random.rand(num_labels, hidden_layer_size + 1)        # Theta2 tiene un tamaño de (2, 11)

# Desenrollar parámetros
nn_params = np.concatenate([Theta1.ravel(), Theta2.ravel()])

print("Dimensiones de Theta1:", Theta1.shape)
print("Dimensiones de Theta2:", Theta2.shape)
print("Dimensiones de nn_params:", nn_params.shape)

Dimensiones de Theta1: (15, 67)
Dimensiones de Theta2: (2, 16)
Dimensiones de nn_params: (1037,)

funcion sigmoid y gradiente

In [ ]:
def sigmoid(z):
    """
    Computes the sigmoid of z.
    """
    return 1.0 / (1.0 + np.exp(-z))


def sigmoidGradient(z):

    g = np.zeros(z.shape)

    g = sigmoid(z) * (1 - sigmoid(z))

    return g

Funcion de costo

In [ ]:
def nnCostFunction(nn_params,
                   input_layer_size,
                   hidden_layer_size,
                   num_labels,
                   X_normalized,  # Cambia X a X_normalized
                   y,
                   lambda_=0.0):

    # Reshape nn_params back into the parameters Theta1 and Theta2, the weight matrices
    # for our 2 layer neural network
    Theta1 = np.reshape(nn_params[:hidden_layer_size * (input_layer_size + 1)],
                        (hidden_layer_size, (input_layer_size + 1)))

    Theta2 = np.reshape(nn_params[(hidden_layer_size * (input_layer_size + 1)):],
                        (num_labels, (hidden_layer_size + 1)))

    m = y.size

    J = 0
    Theta1_grad = np.zeros(Theta1.shape)
    Theta2_grad = np.zeros(Theta2.shape)

    a1 = np.concatenate([np.ones((m, 1)), X_normalized], axis=1)  # Utiliza X_normalized en lugar de X

    a2 = sigmoid(a1.dot(Theta1.T))
    a2 = np.concatenate([np.ones((a2.shape[0], 1)), a2], axis=1)

    a3 = sigmoid(a2.dot(Theta2.T))

    y_matrix = y.reshape(-1)
    y_matrix = np.eye(num_labels)[y_matrix]

    temp1 = Theta1
    temp2 = Theta2

    # Agregar el término de regularización
    reg_term = (lambda_ / (2 * m)) * (np.sum(np.square(temp1[:, 1:])) + np.sum(np.square(temp2[:, 1:])))

    J = (-1 / m) * np.sum((np.log(a3) * y_matrix) + np.log(1 - a3) * (1 - y_matrix)) + reg_term

    # Backpropagation
    delta_3 = a3 - y_matrix
    delta_2 = delta_3.dot(Theta2)[:, 1:] * sigmoidGradient(a1.dot(Theta1.T))

    Delta1 = delta_2.T.dot(a1)
    Delta2 = delta_3.T.dot(a2)

    # Agregar regularización al gradiente
    Theta1_grad = (1 / m) * Delta1
    Theta1_grad[:, 1:] = Theta1_grad[:, 1:] + (lambda_ / m) * Theta1[:, 1:]

    Theta2_grad = (1 / m) * Delta2
    Theta2_grad[:, 1:] = Theta2_grad[:, 1:] + (lambda_ / m) * Theta2[:, 1:]

    grad = np.concatenate([Theta1_grad.ravel(), Theta2_grad.ravel()])

    return J, grad

In [ ]:
lambda_ = 0
J, _ = nnCostFunction(nn_params, input_layer_size, hidden_layer_size, num_labels, X_normalized, y, lambda_)  # Usando X_normalized en lugar de X
print('Costo en parametros (cargado de ex4weights): %.6f ' % J)
print('El costo debe esta cercano a               : 0.287629')

Costo en parametros (cargado de ex4weights): 4.586888
El costo debe esta cercano a               : 0.287629

In [ ]:

z = np.array([-1, -0.5, 0, 0.5, 1] * 66)  # Replicar el arreglo 14 veces para simular 14 columnas
g = sigmoidGradient(z)
print('Gradiente sigmoide evaluado con [-1 -0.5 0 0.5 1] (repetido 14 veces):\n', g)

Gradiente sigmoide evaluado con [-1 -0.5 0 0.5 1] (repetido 14 veces):
 [0.19661193 0.23500371 0.25       0.23500371 0.19661193 0.19661193
 0.23500371 0.25       0.23500371 0.19661193 0.19661193 0.23500371
 0.25       0.23500371 0.19661193 0.19661193 0.23500371 0.25
 0.23500371 0.19661193 0.19661193 0.23500371 0.25       0.23500371
 0.19661193 0.19661193 0.23500371 0.25       0.23500371 0.19661193
 0.19661193 0.23500371 0.25       0.23500371 0.19661193 0.19661193
 0.23500371 0.25       0.23500371 0.19661193 0.19661193 0.23500371
 0.25       0.23500371 0.19661193 0.19661193 0.23500371 0.25
 0.23500371 0.19661193 0.19661193 0.23500371 0.25       0.23500371
 0.19661193 0.19661193 0.23500371 0.25       0.23500371 0.19661193
 0.19661193 0.23500371 0.25       0.23500371 0.19661193 0.19661193
 0.23500371 0.25       0.23500371 0.19661193 0.19661193 0.23500371
 0.25       0.23500371 0.19661193 0.19661193 0.23500371 0.25
 0.23500371 0.19661193 0.19661193 0.23500371 0.25       0.23500371
 0.19661193 0.19661193 0.23500371 0.25       0.23500371 0.19661193
 0.19661193 0.23500371 0.25       0.23500371 0.19661193 0.19661193
 0.23500371 0.25       0.23500371 0.19661193 0.19661193 0.23500371
 0.25       0.23500371 0.19661193 0.19661193 0.23500371 0.25
 0.23500371 0.19661193 0.19661193 0.23500371 0.25       0.23500371
 0.19661193 0.19661193 0.23500371 0.25       0.23500371 0.19661193
 0.19661193 0.23500371 0.25       0.23500371 0.19661193 0.19661193
 0.23500371 0.25       0.23500371 0.19661193 0.19661193 0.23500371
 0.25       0.23500371 0.19661193 0.19661193 0.23500371 0.25
 0.23500371 0.19661193 0.19661193 0.23500371 0.25       0.23500371
 0.19661193 0.19661193 0.23500371 0.25       0.23500371 0.19661193
 0.19661193 0.23500371 0.25       0.23500371 0.19661193 0.19661193
 0.23500371 0.25       0.23500371 0.19661193 0.19661193 0.23500371
 0.25       0.23500371 0.19661193 0.19661193 0.23500371 0.25
 0.23500371 0.19661193 0.19661193 0.23500371 0.25       0.23500371
 0.19661193 0.19661193 0.23500371 0.25       0.23500371 0.19661193
 0.19661193 0.23500371 0.25       0.23500371 0.19661193 0.19661193
 0.23500371 0.25       0.23500371 0.19661193 0.19661193 0.23500371
 0.25       0.23500371 0.19661193 0.19661193 0.23500371 0.25
 0.23500371 0.19661193 0.19661193 0.23500371 0.25       0.23500371
 0.19661193 0.19661193 0.23500371 0.25       0.23500371 0.19661193
 0.19661193 0.23500371 0.25       0.23500371 0.19661193 0.19661193
 0.23500371 0.25       0.23500371 0.19661193 0.19661193 0.23500371
 0.25       0.23500371 0.19661193 0.19661193 0.23500371 0.25
 0.23500371 0.19661193 0.19661193 0.23500371 0.25       0.23500371
 0.19661193 0.19661193 0.23500371 0.25       0.23500371 0.19661193
 0.19661193 0.23500371 0.25       0.23500371 0.19661193 0.19661193
 0.23500371 0.25       0.23500371 0.19661193 0.19661193 0.23500371
 0.25       0.23500371 0.19661193 0.19661193 0.23500371 0.25
 0.23500371 0.19661193 0.19661193 0.23500371 0.25       0.23500371
 0.19661193 0.19661193 0.23500371 0.25       0.23500371 0.19661193
 0.19661193 0.23500371 0.25       0.23500371 0.19661193 0.19661193
 0.23500371 0.25       0.23500371 0.19661193 0.19661193 0.23500371
 0.25       0.23500371 0.19661193 0.19661193 0.23500371 0.25
 0.23500371 0.19661193 0.19661193 0.23500371 0.25       0.23500371
 0.19661193 0.19661193 0.23500371 0.25       0.23500371 0.19661193
 0.19661193 0.23500371 0.25       0.23500371 0.19661193 0.19661193
 0.23500371 0.25       0.23500371 0.19661193 0.19661193 0.23500371
 0.25       0.23500371 0.19661193 0.19661193 0.23500371 0.25
 0.23500371 0.19661193 0.19661193 0.23500371 0.25       0.23500371
 0.19661193 0.19661193 0.23500371 0.25       0.23500371 0.19661193]

# La función randInitializeWeights se utiliza para inicializar aleatoriamente los pesos de una capa en una red neuronal.

In [ ]:
def randInitializeWeights(L_in, L_out, epsilon_init=0.12):
    """
    Randomly initialize the weights of a layer in a neural network.

    Parameters
    ----------
    L_in : int
        Number of incomming connections.

    L_out : int
        Number of outgoing connections.

    epsilon_init : float, optional
        Range of values which the weight can take from a uniform
        distribution.

    Returns
    -------
    W : array_like
        The weight initialiatized to random values.  Note that W should
        be set to a matrix of size(L_out, 1 + L_in) as
        the first column of W handles the "bias" terms."""


    W = np.zeros((L_out, 1 + L_in))
    W = np.random.rand(L_out, 1 + L_in) * 2 * epsilon_init - epsilon_init

    return W

In [ ]:
print('Inicialización de parámetros de redes neuronales...')

initial_Theta1 = randInitializeWeights(input_layer_size, hidden_layer_size)
initial_Theta2 = randInitializeWeights(hidden_layer_size, num_labels)

# Desenrrollr parametros
initial_nn_params = np.concatenate([initial_Theta1.ravel(), initial_Theta2.ravel()], axis=0)

Inicialización de parámetros de redes neuronales...

realiza la optimización de la función de costo de una red neuronal utilizando el método de optimización L-BFGS-B, utilizando los datos normalizados (X_normalized) y el valor de lambda especificado.

In [ ]:
options = {'maxfun': 2000}  # Cambia maxiter a maxfun

#  You should also try different values of lambda
lambda_ = 1

# Create "short hand" for the cost function to be minimized
costFunction = lambda p: nnCostFunction(p, input_layer_size,
                                        hidden_layer_size,
                                        num_labels, X_normalized, y, lambda_)  # Usa X_normalized

# Now, costFunction is a function that takes in only one argument
# (the neural network parameters)
# Establecer el número máximo de iteraciones como un argumento independiente
res = optimize.minimize(costFunction,
                        initial_nn_params,
                        jac=True,
                        method='L-BFGS-B',  # Cambia el método a 'L-BFGS-B'
                        options=options)  # Usa options

# Obtener la solución de la optimización
nn_params = res.x

# Obtener Theta1 y Theta2 de nuevo a partir de nn_params
Theta1 = np.reshape(nn_params[:hidden_layer_size * (input_layer_size + 1)],
                    (hidden_layer_size, (input_layer_size + 1)))

Theta2 = np.reshape(nn_params[(hidden_layer_size * (input_layer_size + 1)):],
                    (num_labels, (hidden_layer_size + 1)))

# **PREDICCIONES**

In [ ]:
def predict(Theta1, Theta2, X):
    """
    Predict the label of an input given a trained neural network
    Outputs the predicted label of X given the trained weights of a neural
    network(Theta1, Theta2)
    """
    # Useful values
    m = X.shape[0]
    num_labels = Theta2.shape[0]

    # You need to return the following variables correctly
    p = np.zeros(m)
    h1 = sigmoid(np.dot(np.concatenate([np.ones((m, 1)), X], axis=1), Theta1.T))
    h2 = sigmoid(np.dot(np.concatenate([np.ones((m, 1)), h1], axis=1), Theta2.T))
    p = np.argmax(h2, axis=1)
    return p

In [ ]:
pred = predict(Theta1, Theta2, X_normalized)  # Usa X_normalized en lugar de X[:,:]
print(pred)
print('Precisión del conjunto de entrenamiento: %f' % (np.mean(pred == y[:]) * 100))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]
Precisión del conjunto de entrenamiento: 100.000000

In [ ]:
pred = predict(Theta1, Theta2, Xp[:,:])
print(pred)
print('Precisión del conjunto de entrenamiento: %f' % (np.mean(pred == yp[:]) * 100))

[0 0 0 ... 0 0 0]
Precisión del conjunto de entrenamiento: 94.109834